version: 1
services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todoApp.wsgi --log-file=-"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key # 環境に合わせて適切なシークレットキーを設定
      - key: DATABASE_URL
        value: postgres://user:password@localhost:5432/yourdatabase # RenderのPostgres URLに変更
      - key: SUPERUSER_EMAIL
        value: admin@example.com # デフォルトスーパーユーザーのメールアドレス
      - key: SUPERUSER_NAME
        value: admin # デフォルトスーパーユーザー名
      - key: SUPERUSER_PASSWORD
        value: password123 # デフォルトスーパーユーザーパスワード（必要に応じて設定）
    plan: free
