# Generated by Django 4.2.6 on 2024-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0008_auto_20191202_0809"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
