# Generated by Django 4.2.6 on 2024-06-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0009_todo_order_alter_todo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
