# Generated by Django 4.2.6 on 2024-07-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0011_rename_iscompleted_todo_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="notification_lead_time",
            field=models.IntegerField(default=0),
        ),
    ]
