# Generated by Django 4.2.6 on 2024-09-04 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0013_fcmdevice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="is_completed",
            new_name="iscompleted",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="updated_at",
            new_name="update_at",
        ),
    ]
