# Generated by Django 4.2.6 on 2024-09-04 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0014_rename_is_completed_todo_iscompleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="iscompleted",
            new_name="isCompleted",
        ),
    ]
